### ISSUE TITLE
Custom Objects not loading

### ISSUE THREAD

**Issue by ellwoodb** [Deli-Collective/DeliCounter#3]
Hi,
for me everything works fine but when I go to the custom objects there is nothing.
Thanks in advance!

![image](https://user-images.githubusercontent.com/73251578/109522084-3e1e3f80-7aae-11eb-87dd-3203b6c1037b.png)

**Comment by nrgill28** [comment]
Ah! Yes I've not gotten around to adding any custom objects into the database yet, they will be coming soon. Since BoneTome has no public API each mod has to be written into the database by hand and it can take some time.

I've been putting it off for a while but I'll go and add a number of them into there right now 😅

**Comment by ellwoodb** [comment]
Ah, ok thank you.
